### ISSUE TITLE
test: vge/vui/mintheme; gs.GetImage undefined (type *vglyph.GlyphSet has no field or method GetImage)

### ISSUE THREAD

**Issue by mewmew** [lakal3/VGE#14]
The `GetImage` method of `GlyphSet` seem to have been renamed or removed, thus causing the test to fail.

```
$ go test ./vge/vui/mintheme
# github.com/lakal3/vge/vge/vui/mintheme [github.com/lakal3/vge/vge/vui/mintheme.test]
vge/vui/mintheme/theme_test.go:32:23: gs.GetImage undefined (type *vglyph.GlyphSet has no field or method GetImage)
FAIL	github.com/lakal3/vge/vge/vui/mintheme [build failed]
FAIL
```

**Comment by lakal3** [comment]
To run this test, you must run test with tag test to enable GetImage method that is for tests only
`go test -tags test
`

Is there any better way to expose methods for tests only?

**Comment by mewmew** [comment]
> Is there any better way to expose methods for tests only?

If it would have been the same package then using `foo_test.go` would have been enough. As they are part of different packages, using a `test` Go build tag is probably the easiest approach.
